// Generated by https://quicktype.io

export class respuestaRendicon {
  idRendicion:        number | undefined;
  nombreArchivo:      string | undefined
  codigoNegocio:      string | undefined;
  idPlantilla:        number | undefined;
  plantillaResultado: string | undefined;
  usuario:            string | undefined;
  fechaModificacion:  String | undefined;
}
