// Generated by https://quicktype.io

export class templateRendicion {
  idPlantilla:       number | undefined;
  nombrePlatilla:    string | undefined;
  descripcion:       string | undefined;
  plantilla:         string | undefined;
  usuario:           string | undefined;
  fechaModificacion: null | undefined;
}
